### ISSUE TITLE
AppImage doesn't start

### ISSUE THREAD

**Issue by gitnaute** [mar0x/Candle#1]
**Versions**
 - Candle version: Candle-1.1.9-x86_64.AppImage
 - Firmware version: 1.1f

**PC info**
- OS:Debian 11
- OpenGL version: 4.5

**Describe the bug**
The application doesn't start: nothing happens when I click on it.

**Additional context**
The currently installed version of Candle 1.1.7 works perfectly.
I have other applications in AppImage format that also work perfectly.

**Comment by mar0x** [comment]
Hello,
Please try to make downloaded appimage executable with `chmod a+x Candle-1.1.9-x86_64.AppImage` and start it from terminal session: `./Candle-1.1.9-x86_64.AppImage`.

Then share output messages.

**Comment by gitnaute** [comment]
Hello marOx,
   I had already made the file executable, as always with AppImages, but I hadn't thought of launching it from the terminal.
   Here's the error message:
   qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
   This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
   What do you recommend to fix this problem?
   
  
   Best regards.
   
  
    
   
  
    
   
  
   Le 21/08/2023 12:44 CEST, Max ***@***.***> a écrit :
   
   
   Hello,Please try to make downloaded appimage executable with chmod a+x Candle-1.1.9-x86_64.AppImage and start it from terminal session: ./Candle-1.1.9-x86_64.AppImage.

**Comment by mar0x** [comment]
I admit that image was incomplete. I've re-build and re-upload the [Candle-1.1.9-x86_64.AppImage](https://github.com/mar0x/Candle/releases/download/v1.1.9/Candle-1.1.9-x86_64.AppImage).
Please download and try start it again.

**Comment by gitnaute** [comment]
Here's the return for this new version:

`/tmp/.mount_Candle7C8LuV/usr/bin/Candle:``` /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/Candle)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/Candle)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Widgets.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libudev.so.1)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libudev.so.1)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libicuuc.so.70)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libicuuc.so.70)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Candle7C8LuV/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Candle7C8LuV/usr/bin/Candle: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by `/tmp/.mount_Candle7C8LuV/usr/bin/../lib/libglib-2.0.so.0)

Friendly

**Comment by mar0x** [comment]
Well, I'll try to rebuild the image on ubuntu-18.04 to avoid use of recent versions API and let you know.

**Comment by gitnaute** [comment]
OK!
Thank you very much for taking the trouble to try and solve this problem.
So, if I understand correctly, an application in .AppImage format doesn't necessarily work on all systems and must therefore be adapted to the target system.
I thought the whole point of this format was its portability.

Friendly.

**Comment by mar0x** [comment]
AppImage is a method to distribute and run binaries in custom environment. They have a requirements (or recommendations) to build images in old distributions for better compatibility. AppImage itself does not provide compatibility "magically" :)

Here is [Candle-1.1.9-qt-5.9.5-x86_64.AppImage](https://github.com/mar0x/Candle/releases/download/v1.1.9/Candle-1.1.9-qt-5.9.5-x86_64.AppImage) built on ubuntu-18.04.6. I hope it will be compatible with your runtime environment.

[Candle-1.1.9-Linux-x86_64.AppImage](https://github.com/mar0x/Candle/releases/download/v1.1.9/Candle-1.1.9-Linux-x86_64.AppImage) should also work.

**Comment by gitnaute** [comment]
Wonderful: it works perfectly. Thank you so much for your work.

> AppImage itself does not provide compatibility "magically"

I'm well aware that none of this happens by magic. Some time ago, I went to look at the documentation on docs.appimage.org because I was thinking of creating AppImages for Candle and FlatCam. I quickly realized that I didn't have the right level of expertise. So once again, thank you very much.
